name: "Develop CI/CD"

on:
  push:
    branches: [suite-menu]
    tags:
      - "*"

jobs:
  build:
    name: IVA Build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone IVA repository with JSOrolla
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install bower dependecy
        run: npm install bower
      - name: Run npm ci 
        run: npm ci --only-production --ignore-scripts
      - name: Run npm install
        run: npm init -y && npm install
      - name: Build IVA app
        run: npm run build
      - name: Upload webpack artifact
        uses: actions/upload-artifact@v2
        with:
          name: webpack-artifact
          path: build
          retention-days: 2

  test:
    name: IVA Tests
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        browsers: [chrome, firefox]
    steps:
      - name: Clone IVA repository with JSOrolla
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node.version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install bower dependency
        run: npm install bower
      - name: Run npm install
        run: npm init -y && npm install
      - name: Test Iva - Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          browser: ${{ matrix.browsers }}
          spec: |
            cypress/integration/001-header-bar-pre-login.spec.js
            cypress/integration/002-login.js
          wait-on: http://localhost:3000
        env:
          cypress_username: demouser
          cypress_password: demouser
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-${{ matrix.browsers }}_${{ matrix.node-version }}
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 2
#      - name: Upload Video
#        uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: cypress-videos-${{ matrix.browsers }}_${{ matrix.node-version }}
#          path: cypress/videos
#          retention-days: 2

  docker:
    name: Publish Docker image in Docker Hub repository
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Download webpack artifact
        uses: actions/download-artifact@v2
        with:
          name: webpack-artifact
          path: build
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and publish Docker image
        run: python3 ./docker/docker-build.py push --images app --tag 2.1.0-exp

  deploy-ucam:
    name: Deploy Web App in UCam
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Download Webpack artifact
        uses: actions/download-artifact@v2
        with:
          name: webpack-artifact
          path: build
      - id: package-version
        name: Read package.json
        uses: "tyankatsu0105/read-package-version-actions@v1"
      - name: Web Delivery
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /mnt/data/WEB-APPS/dev/iva-${{ steps.package-version.outputs.version }}
          rmRemote: true
          host: ${{ secrets.SSH_SWDEV_IP }}
          username: ${{ secrets.SSH_SWDEV_USER }}
          password: ${{ secrets.SSH_SWDEV_PASSWORD }}
